# SECURITY WARNING: keep the secret key used in production secret!
# $ cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 49;echo
# SECRET_KEY:

# Development env open this, when error occur display the full process track, Production disable it
DEBUG: False

# DEBUG, INFO, WARNING, ERROR, CRITICAL can set. See https://docs.djangoproject.com/en/1.10/topics/logging/
LOG_LEVEL: DEBUG
LOG_FILES: logs/OpenVPNWEBUI.log

# Session expiration setting, Default 1 hour, Also set expired on on browser close
SESSION_COOKIE_AGE: 3600


# Database setting, Support sqlite3, mysql, postgres ....
# See https://docs.djangoproject.com/en/1.10/ref/settings/#databases
# DB setting:
DB_ENGINE: mysql
DB_HOST: 127.0.0.1
DB_PORT: 3306
DB_USER: root
DB_PASSWORD: rootroot
DB_NAME: ovpnmgmt

# When Django start it will bind this host and port
# ./manage.py runserver 127.0.0.1:8080
HTTP_BIND_HOST: 0.0.0.0
HTTP_LISTEN_PORT: 8080
WS_LISTEN_PORT: 8070

