#!/bin/sh

# This is explicitly in /bin/sh (==DASH shell on Ubuntu) for faster startup time
# This script MUST be readable by openvpn user

# DELETE actions dont get the 'config' env var - so we set explicitly for python script to use
if [ -z ${config+x} ]; then export config=server-tcp.conf ; fi

echo "ionice -c3 nice -n 15 /etc/openvpn/server/learn-address-route53-wrapper $1 $2 $3" | at -M now >/dev/null 2>/dev/null
exit 0
